### ISSUE TITLE
feat+1: please add L2 support, OE and Arbitrum

### ISSUE THREAD

**Issue by niknovikov1** [chunza2542/uniswapv3-calculator#10]
Hi - great tool and thx for sharing!
would it be possible to add L2 support for Optimism and Arbitrum?
I tried to replace the graph URL to OE but apparently token addresses have to be retrieved somehow differently too and my coding skills are not good enough to change myself.
Best,
Nikolai

**Comment by chunza2542** [comment]
Sure, I've planned to integrate L2 as soon as I've got a free time. maybe the end of the year, I guess. quite busy these days 🤯.
