### ISSUE TITLE
Pair select issue

### ISSUE THREAD

**Issue by DIMNDio** [chunza2542/uniswapv3-calculator#12]
hi, seems to be an issue with token selection.
it just gets stuck on loading...
<img width="998" alt="Screenshot 2021-11-14 at 09 58 33" src="https://user-images.githubusercontent.com/32847841/141672736-adfdb559-49de-460a-9d47-4ace3ef70671.png">
..

**Comment by chunza2542** [comment]
@DIMNDio can you try it again? I just test it and it's works

**Comment by zanussbaum** [comment]
Same thing occurs for me if I try to select ETH/ENS pair, the app just hangs

**Comment by marcowells10** [comment]
it just hangs with ETH/RWASTE also, pls fix
