### ISSUE TITLE
Adjusting Min Value changes Max value.

### ISSUE THREAD

**Issue by Emperornero** [chunza2542/uniswapv3-calculator#18]
Hey Chun,

Great app.  Possible to make it so the 2 Min/Max fields are independent of each other?

Kind of frustrating when you're typing in a number in Min Price and have to type in the Max Price again, if you've already set it.  Easy to do when trying to calculate multiple positions.

**Comment by chunza2542** [comment]
@Emperornero could you help provide a step to reproduce the problem? I'll look into it. Thanks for reporting.

**Comment by Emperornero** [comment]
Please see attached! 

![regfera](https://user-images.githubusercontent.com/10823892/167235565-cf56455c-def8-42b2-8387-e4c80641e67f.gif)

**Comment by chunza2542** [comment]
fixed! sorry for my late response.
