### ISSUE TITLE
Polygon USDC/ETH estimated fee calculations

### ISSUE THREAD

**Issue by futuretoothdoc** [chunza2542/uniswapv3-calculator#25]
Are the USDC/ETH estimated fee calculations correct?  The estimated fees look very high - when you go to select a min and max price they appear to be reversed to start - didn't know if the estimated collection fees were really this high or if there was a bug in the software for the estimation with min/max price.  Thank you!!

**Comment by chunza2542** [comment]
Thanks for reporting, I'll take a look. would be great if you could provide a screenshot.

**Comment by dexpad-dev** [comment]
Just checked Polygon USDC/ETH and the fees look way higher. The actual fee I received in last 24 hours is 1/10th of the fee showing.

**Comment by futuretoothdoc** [comment]
I think the software code is reading the max input price as a minimum - and is also reading the min input price as a maximum..try one out and look where the bars start on the correlation graph..think that is the bug!

**Comment by chunza2542** [comment]
Updated! @dexpad-dev @futuretoothdoc could you try it again?

**Comment by dexpad-dev** [comment]
Looks much closer to the actual fees received now. I will have 8 hours more to calculate.
Thanks for the fix @chunza2542 I am thinking of contributing to making autocompounder for v3. Would love to collab?

**Comment by futuretoothdoc** [comment]
> Updated! @dexpad-dev @futuretoothdoc could you try it again?

Chunza - looks great mate!  Appreciate all the help and hard work you put into this!!!  Sorry to be that guy!!

**Comment by chunza2542** [comment]
> I am thinking of contributing to making autocompounder for v3. Would love to collab?

@dexpad-dev I also have planned to implement position management features (at the end of the year), would be great to integrate the autocompounder.
