### ISSUE TITLE
Handle "Unable to find token from contract address" Error

### ISSUE THREAD

**Issue by mikejr83** [chunza2542/uniswapv3-calculator#6]
When certain tokens are selected, Tokemak (0x2e9d63788249371f1DFC918a52f8d799F4a38C94) for instance, an error is thrown:

```
Uncaught (in promise) Error: Unable to find token from contract address "0x2e9d63788249371f1dfc918a52f8d799f4a38c94"
```

When this occurs the app is broken and a refresh is needed to continue. Also there is no information presented to the user to alert them. I was wondering why the loading image was spinning forever so I decided to take a look at app and noticed this error.

**Comment by chunza2542** [comment]
Thanks for your reporting, I'll take a look at it
